---
language: python
services: docker

#env:
#  - PLESK_VERSION=PLESK_12_5_30
#  - PLESK_VERSION=PLESK_12_0_18
#  - PLESK_VERSION=PLESK_11_5_30

install:
  - pip install ansible molecule ansible-lint docker

script:
  # Run tests with molecule
  - travis_wait molecule converge

# vi: ts=2 sts=2 et sw=2 tw=80
